### ISSUE TITLE
modal loading - broken layout

### ISSUE THREAD

**Issue by kapsr** [particl/partgui#314]
After initial "quote" screen appearance, a new screen appears for a few milliseconds/seconds before the blockchain starts syncing. Layout is off, get rid of screen completely as quote was displayed already in prior screen (or fix layout).

![untitled-1](https://user-images.githubusercontent.com/32437236/32641752-fb96db72-c5cf-11e7-82a1-1d8c79fe06a6.jpg)

**Comment by pciavald** [comment]
any idea why this happens @kewde ?

**Comment by anandsinghparihar** [comment]
@pciavald I am checking it !!

**Comment by kewde** [comment]
This is for any modal I believe. I did this on purpose, but the css changes have broken it.

**Comment by anandsinghparihar** [comment]
@allienworks  could you please have look

**Comment by allienworks** [comment]
Seems like this happens on Win only. Does anybody have this bug on Linux/Mac as well?

**Comment by pciavald** [comment]
I had it too on linux

**Comment by allienworks** [comment]
I had some trouble setting up my Win machine for dev, but it seems that the issue is connected to this `*ngIf="!syncPercentage"` block: https://github.com/particl/partgui/blob/develop/src/app/modals/syncing/syncing.component.html#L48

This whole block isn't needed at all IMO. It has almost the same contents as the intro splash screen and it's never used (just blinks before the `*ngIf="syncPercentage` fires up). I removed the whole block locally and seems to solve this issue.

Not sure who had fingers in it before, can someone confirm if it's OK? @kewde

**Comment by pciavald** [comment]
seems I added this in july https://github.com/particl/partgui/commit/49114816b8b1cdbb55d3cf9b0bb0777f7f17cb62

**Comment by allienworks** [comment]
I don't see it at all on my Linux machine, on my Win it just blinks for a fraction of second.
**Can someone else confirm how long they see it before it disappears?**

It doesn't really serve any purpose (from what I see), so I would get rid of it.
The styling is messed because it inherits styles from splash screen, which is dark.

**Comment by allienworks** [comment]
^ created PR for this. If you can, please test if it still behaves badly.

**Comment by pciavald** [comment]
![](https://i.pinimg.com/736x/b6/41/67/b64167994e7d0fca2485268092a6ce12--pi-pie-butter-pie.jpg)
