### ISSUE TITLE
wrong mnemonic check should trigger a descriptive error

### ISSUE THREAD

**Issue by SativaL** [particl/partgui#331]
while generating a new mnemonic seed you copy it and then re-enter it again. In most client you are forced to re-copy it after you click next, this is okay. I dont know if this is wanted how it currently is that you cant just copy to clipboard and then ctr+v to re-enter everything (it wont let you do this, if you try to re enter with copy and paste it will re enter all of the seed into one word text field).

I remember from other services that once you copied and saved the seed you are able to just click ctrl+v and paste them completely and proceed. (Makes it more easy to proceed instead of writing some single words). 

Also if you click next with a wrong seed entered you should be getting a small information that the seed entered was incorrect.

**Comment by kewde** [comment]
1. On purpose, we want to make sure they actually look at their seed and verify it.
2. There are some error message (straight from the daemon) pop ups, but they aren't refined for great UX.

**Comment by HenkSwardt** [comment]
@EagleEye25 will look into this fr us.

Please look at this point for us:
"Also if you click next with a wrong seed entered you should be getting a small information that the seed entered was incorrect."

As stated by @kewde some of the other behavior is intentional, and the pasting into a single box has been resolved.

**Comment by HenkSwardt** [comment]
Issue has been resolved. 

https://github.com/particl/partgui/pull/418
