### ISSUE TITLE
Send > Dropdown should be proper align 

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/partgui#468]
In send page, the PART dropdown is displayed small, it should be proper align 
![send-dropdown](https://user-images.githubusercontent.com/17725557/33672251-cb3717a2-dacf-11e7-8730-fbe951922947.png)

**Comment by EagleEye25** [comment]
i have had a look at the issue, and consulted with ryno, as i couldnt get hold of kiriti at the moment and he states that its perfect as is, so no need for any change

**Comment by HenkSwardt** [comment]
Closing issue as per above discussion

**Comment by anandsinghparihar** [comment]
Small input does not look good we should divide it like as it was 
![screenshot from 2017 12 08 13 16 09](https://user-images.githubusercontent.com/17725557/33756152-287b6bca-dc1a-11e7-9b04-8242633a208b.png)

**Comment by gerlofvanek** [comment]
Please make it look like the screenshot below: 
![Align](https://i.gyazo.com/af0bd7cff1c3ff9aa94273c26366da6e.png)

I think since the material upgrade some items are not styled properly anymore. Please keep the layouts consistent, and align inputs in proper manner. The drop down (currency one) is missing the underline.

**Comment by EagleEye25** [comment]
i will get on it now

**Comment by anandsinghparihar** [comment]
In narration, case may be dropwon not look good so we should set width 30% to dropdown and 70% to input. as @gerlofvanek suggested

**Comment by EagleEye25** [comment]
fixed: https://github.com/particl/partgui/pull/486

**Comment by gerlofvanek** [comment]
@EagleEye25 Thanks!, can you add the bottom border line under PART, same as the input fields? And make it 70% (input) / 30% (drop-down) as @anandsinghparihar screenshot.

**Comment by EagleEye25** [comment]
will do so

**Comment by EagleEye25** [comment]
done: 
![ss 2017-12-08 at 01 23 20](https://user-images.githubusercontent.com/28861857/33763934-09cf76de-dc1b-11e7-8810-b306cddc8efb.png)

**Comment by allienworks** [comment]
I've done the change from full-width "amount input & select" to smaller ones.

My reasoning was that the select looks really bad when large like that (+ don't forget that it doesn't really do anything now, because there's just one option).

Regarding the input - it's also very redundant to have it so large, when even if you'd send all the PARTs in existence (with all the 8 decimal places), it would take up about 25% of the whole space of the input.

That's why I did it like this:

![](https://user-images.githubusercontent.com/17725557/33672251-cb3717a2-dacf-11e7-8730-fbe951922947.png)

So we can make the elements small/big as needed and perhaps reogranize them a bit (I was also preparing my ground a bit for the planned Send page redesign - it would come in handy there). Not just mindlessly expand everything to 100% width.. But surely this is just my opinion :)

**Comment by gerlofvanek** [comment]
@EagleEye25 Thanks!
@allienworks Agreed!,

Fix we can keep for now is the bottom border line under PART @ drop-drown. And because @allienworks will be doing Send page redesign, lets get it back in the current state (from full-width "amount input & select" to smaller ones.)
