### ISSUE TITLE
Empty Dialog Modal 

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/partgui#484]
Empty modal open if no wallet exists. display `Error: Loading block index.`

![empty-modal](https://user-images.githubusercontent.com/17725557/33711973-d6d5684c-db6b-11e7-8774-4151491948ea.png)

**Comment by anandsinghparihar** [comment]
this error does not occur again but I saw this error sometimes we need to debug it in which case its display empty?

**Comment by pciavald** [comment]
Can't handle this now, i have too much on the waiting line. @HenkSwardt ?

**Comment by pciavald** [comment]
yes
i think it's a bit random
it depends how fast the daemon manages to start => if an RPC call is issued before the daemon is ready
this issue will be fixed anyway because the gui will be avoided from making calls while the daemon is not ready
but it doesn't mean that we shouldn't fix the empty modal problem
because it could pop for another reason

**Comment by vikas-cis** [comment]
@pciavald I have added daemon error messages on the left side menu and get rid of the ugly modals. Please have a look and let me know 

Thanks

**Comment by pciavald** [comment]
should be fixed
