### ISSUE TITLE
Add "Warning message" to Particl Wallet for important messages 

### ISSUE THREAD

**Issue by LiteBit** [particl/partgui#489]
# Users don't have any warning if their wallet app is compromised by code issues without going to Github to find out

Shortly after Particl Wallet 1.0.0 was released a vulnerability was found in the Mac build of the wallet. @particldev tweeted that a vulnerability was found with OSX but no follow up was ever made. Or explaination. 

@kewde made a quick fix and added it as pre-release, but nothing ever happened. 

Meanwhile users still don't have answers and don't know they are still using a wallet with issues.

I think having a banner warning system that is red, orange, yellow, green would be helpful.

**Comment by allienworks** [comment]
So this is pretty much the same as https://github.com/particl/partgui/issues/488, right? If there would be a notification for any new releases (stable & bugfixes etc.), that would be enough.

Because I think that due to security vulnerabilities, we decided not to connect the client to any external points (like we had a RSS from blog before), so sending "customized" messages based on what's currently needed might not go.

Therefore I think that "new update" notification would be enough (at least for now). We could prepare notifications for other cases as well, but I can't think of anything else now tbh.
