### ISSUE TITLE
History Tab labels to be in past tense

### ISSUE THREAD

**Issue by HenkSwardt** [particl/partgui#583]
Please can we change the history page tab labels to reflect past tense. 

![image](https://user-images.githubusercontent.com/28799964/34558688-bc8cd64a-f147-11e7-8666-1406bfda708d.png)

Send - Sent
Receive - Received
Stake - Staked
Balance Transfer - Balances Transferred

**Comment by pciavald** [comment]
@HenkSwardt when we've made these terms with @allienworks we chose that in order not to confuse the savvy guys who will use the console and the filtertransaction API.
I personnaly always get mixed up with past tenses and plurals in arguments, so we've put the tabs with the same name than the arguments to try not to mix people up. What do you think ? More user friendly or more coherent ? @rynomster

**Comment by allienworks** [comment]
My opinion was that we should have it in past tense (Received, Sent..) because it's natural and it makes more sense.

I understand your reasoning @pciavald, but IMO those savvy users who use console won't really use/depend on this GUI. In other words the majority of the users using this will be rather newbies IMO.

Related to this, I think it's really important to discuss and decide the big picture approach – for who are we making this product (and the whole project)? Are we pushing to masses (and therefore everything should be really foolproof) or do we want to appeal to privacy-oriented geeks mainly?

I suppose we're more after the mainstream and that means that every decision we make regarding not just UX should go hand in hand with this.

**Comment by pciavald** [comment]
My position on this question would be that it's designed for newbies and usable by savvies. Regarding this it would make sense to have the design in past tense and for instance console available in the GUI (#470).

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/partgui/pull/585

**Comment by allienworks** [comment]
Wouldn't be "Balance Transfers" better? I don't think that everything has to be in past tense, here it doesn't make that much sense IMO.. What do you think?
